

<!--content end-->
</div>

<footer>
    <nav>
        <ul>
            <li><a href="terms.php">Terms &amp; Conditions</a></li>
            <li><a href="faq.php">FAQ</a></li>

        </ul>
    </nav>
    <p>Copyright &copy;2014 Arrow Photography. All rights reserved.</p>
</footer>
</div>

<script src="assets/libs/min/jquery.min.js"></script>
<script src="assets/js/scripts.js"></script>

</body>
</html>